Ajout d'un module de logging
ClubCedille/mattermost2discord pull request #19
Opened 2021-02-13 04:20 UTC by notarock

- Utilise  [zap](https://github.com/uber-go/zap)
- Module singleton pour logger les erreurs et autres messages au format json dans la console
- Ferme #15

2021-02-13 04:35 UTC, cguertin14 approved these changes
lgtm. finalement avais-tu esssayé init?

2021-02-13 04:38 UTC, notarock commented
> lgtm. finalement avais-tu esssayé init?

Nope, mais je pourrais revenir pour changer ça prochainement!

2021-02-13 15:39 UTC, Vboivin commented
@notarock vraiment nice! Est-ce que tu as un exemple des outputs?

2021-02-13 15:40 UTC, Vboivin approved these changes

2021-02-13 21:24 UTC, berbiche requested changes
Petite question sur l'initialization du logger

2021-02-13 21:24 UTC, berbiche commented on api/discord_bot.go
> +	)
Étant donné qu'il n'y aura pas de messages confidentiels envoyés, le logging ne pose pas de problème.
Dans tous les cas, ça peut être revus avec une variable d'environnement en production je présume?

2021-02-13 21:24 UTC, berbiche commented on api/log.go
> +			logger, _ := zap.NewProduction()
c'est quoi le second parametre, une erreur?
est-ce qu'on devrait panic si on arrive pas a initialize le logger?

2021-02-13 21:53 UTC, cguertin14 commented on api/log.go
> +			logger, _ := zap.NewProduction()
si on se fie au quickstart de leur documentation, c'est la manière recommandée de le faire: https://github.com/uber-go/zap#quick-start

2021-02-13 21:57 UTC, Vboivin commented on api/discord_bot.go
> +	)
@berbiche On pourrait rajouter une variable d'environnement du style VERBOSE et faire un if check pour cette portion là du code. Ça pourrait être utile d'avoir ce toggle si jamais on veut transmettre des trucs confidentiels.

2021-02-14 03:24 UTC, notarock commented on api/log.go
> +			logger, _ := zap.NewProduction()
>  est-ce qu'on devrait panic si on arrive pas a initialize le logger?

Pense pas 

> c'est quoi le second parametre, une erreur?

Oui

2021-02-14 03:37 UTC, notarock commented on api/discord_bot.go
> +	)
Comment est-ce qu'on voudrait activer ce toggle? Une variable d'environnement serait difficile à gerer assumant que le bot roule sur notre infra. Ca serait alors "toute ou pentoute" en ce qui concerne le logging des messages. Mais ca dépend...

Est-ce que on voudrait le désactiver pour une période de temps ou bien dépendant du message? Ou bien plutôt l'activer quand on développe, par exemple? Pour ça, je pense que d'avoir un moyen de passer `--verbose` ou `-v` en ligne de commmande ça serait le best. Pour la deuxième option, je sais pas trop comment c'est planifié pour le moment, mais si il faut faire une commande sur mattermost pour indiquer qu'un message doit être relayé vers discord, on pourrait avoir un flag qui se situe directement dans le message.

Vous en pensez quoi?

2021-02-14 03:44 UTC, berbiche commented on api/log.go
> +			logger, _ := zap.NewProduction()
Ok, je presume que ca va pousser le panic au moment où va utiliser les methodes sur un instance de logger null

2021-02-14 03:53 UTC, Vboivin commented on api/discord_bot.go
> +	)
@notrock Nooooice! Oui c'est une bonne idée directement dans le message mattermost et on rajoute une petite logique de parsing! Comme ça, on n'a pas besoin de toggle rien ou de passer d'arguments de commandes.

Du style: "2disc secret <notre message de mattermost>", puis on ne log pas le message si secret ou whatever identifiant qu'on veut utiliser est présent.

2021-02-14 04:07 UTC, notarock commented
> @notarock vraiment nice! Est-ce que tu as un exemple des outputs?

J'ai un exemple dans le logs des tests:
<details>
  <summary>logs</summary>

```
=== RUN   TestCreateDiscordBot
--- PASS: TestCreateDiscordBot (0.00s)
=== RUN   TestDiscordBotGetPayload
--- PASS: TestDiscordBotGetPayload (0.00s)
=== RUN   TestDiscordBotGetPayloadError
{"level":"error","ts":1613190466.9995167,"caller":"api/discord_bot.go:50","msg":"GetPayloadErrorinvalid request","stacktrace":"github.com/ClubCedille/mattermost2discord/api.(*DiscordBot).GetPayload\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/discord_bot.go:50\ngithub.com/ClubCedille/mattermost2discord/api.TestDiscordBotGetPayloadError\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/discord_bot_test.go:44\ntesting.tRunner\n\t/opt/hostedtoolcache/go/1.15.8/x64/src/testing/testing.go:1123"}
--- PASS: TestDiscordBotGetPayloadError (0.00s)
=== RUN   TestDiscordBotGetContent
--- PASS: TestDiscordBotGetContent (0.00s)
=== RUN   TestDiscordBotSendMessage
{"level":"info","ts":1613190467.1394746,"caller":"api/discord_bot.go:32","msg":"Sending message to discord%!(EXTRA zapcore.Field={user 15 0 test <nil>}, zapcore.Field={message 15 0 test <nil>}, zapcore.Field={Channel 15 0 test <nil>})"}
{"level":"error","ts":1613190467.140058,"caller":"api/discord_bot.go:39","msg":"DiscordMessageErrorHTTP 401 Unauthorized, {\"message\": \"401: Unauthorized\", \"code\": 0}","stacktrace":"github.com/ClubCedille/mattermost2discord/api.(*DiscordBot).SendMessage\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/discord_bot.go:39\ngithub.com/ClubCedille/mattermost2discord/api.TestDiscordBotSendMessage.func1\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/discord_bot_test.go:83\ngithub.com/stretchr/testify/assert.didPanic.func1\n\t/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1018\ngithub.com/stretchr/testify/assert.didPanic\n\t/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1020\ngithub.com/stretchr/testify/assert.NotPanics\n\t/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1091\ngithub.com/ClubCedille/mattermost2discord/api.TestDiscordBotSendMessage\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/discord_bot_test.go:82\ntesting.tRunner\n\t/opt/hostedtoolcache/go/1.15.8/x64/src/testing/testing.go:1123"}
--- PASS: TestDiscordBotSendMessage (0.14s)
=== RUN   TestPanicIfDiscordBotMissesInformation
--- PASS: TestPanicIfDiscordBotMissesInformation (0.00s)
=== RUN   TestLoggerIsSameInstance
{"level":"info","ts":1613190467.1424038,"caller":"api/log_test.go:10","msg":"Testing logger"}
--- PASS: TestLoggerIsSameInstance (0.00s)
=== RUN   TestServerDiscordMessageError
{"level":"info","ts":1613190467.1424549,"caller":"api/server.go:29","msg":"Server setup done."}
{"level":"info","ts":1613190467.1902058,"caller":"api/discord_bot.go:32","msg":"Sending message to discord%!(EXTRA zapcore.Field={user 15 0 hello <nil>}, zapcore.Field={message 15 0 hello <nil>}, zapcore.Field={Channel 15 0 test <nil>})"}
{"level":"error","ts":1613190467.1902308,"caller":"api/discord_bot.go:39","msg":"DiscordMessageErrorHTTP 401 Unauthorized, {\"message\": \"401: Unauthorized\", \"code\": 0}","stacktrace":"github.com/ClubCedille/mattermost2discord/api.(*DiscordBot).SendMessage\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/discord_bot.go:39\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\ngithub.com/ClubCedille/mattermost2discord/api.HandleBotError\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/server.go:34\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\ngithub.com/gin-gonic/gin.RecoveryWithWriter.func1\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367\nnet/http.serverHandler.ServeHTTP\n\t/opt/hostedtoolcache/go/1.15.8/x64/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/opt/hostedtoolcache/go/1.15.8/x64/src/net/http/server.go:1925"}
{"level":"error","ts":1613190467.190265,"caller":"api/server.go:38","msg":"HTTP 401 Unauthorized, {\"message\": \"401: Unauthorized\", \"code\": 0}","stacktrace":"github.com/ClubCedille/mattermost2discord/api.HandleBotError\n\t/home/runner/work/mattermost2discord/mattermost2discord/api/server.go:38\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\ngithub.com/gin-gonic/gin.RecoveryWithWriter.func1\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367\nnet/http.serverHandler.ServeHTTP\n\t/opt/hostedtoolcache/go/1.15.8/x64/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/opt/hostedtoolcache/go/1.15.8/x64/src/net/http/server.go:1925"}
[GIN] 2021/02/13 - 04:27:47 | 400 |   47.144178ms |       127.0.0.1 | POST     "/v1/discord-message/"
Error #01: HTTP 401 Unauthorized, {"message": "401: Unauthorized", "code": 0}
--- PASS: TestServerDiscordMessageError (0.05s)
=== RUN   TestServerHealthCheck
{"level":"info","ts":1613190467.1909974,"caller":"api/server.go:29","msg":"Server setup done."}
[GIN] 2021/02/13 - 04:27:47 | 200 |        22.1µs |       127.0.0.1 | GET      "/health/"
--- PASS: TestServerHealthCheck (0.00s)
PASS
coverage: 100.0% of statements
```

</details>

2021-02-16 17:38 UTC, Vboivin commented on api/discord_bot.go
> +	)
@berbiche On a décidé de continuer avec l'implémentation de @notarock parce qu'on ne pense pas envoyer des messages confidentiels. L'implémentation est simplement pour des annonces ou des événements. Dans le futur, on pourrait l'ajouter.

2021-02-17 04:53 UTC, berbiche approved these changes

2021-02-20 07:33 UTC, merged