Configuration doc
ClubCedille/mattermost2discord pull request #25
Opened 2021-05-28 00:57 UTC by SonOfLope

-  Added uml diagram of the rest API process
- Added documentation on how to set up mattermost webhook and the discord bot
- This closes #23

2021-05-28 13:43 UTC, cguertin14 requested changes

2021-05-28 13:43 UTC, cguertin14 commented on README.md
> +
Dans le diagramme de séquence, le step "web/http" n'est pas nécessaire. Par contre, le reste est excellent 💯.

2021-05-28 13:43 UTC, cguertin14 commented on mm2disc_uml.plantuml
> +ActorFontName Aapex
p-ê rajouter un tab pour chaque item ici, pour une meilleure indentation

2021-05-29 17:40 UTC, SonOfLope commented on mm2disc_uml.plantuml
> +ActorFontName Aapex
Done!

2021-05-29 17:40 UTC, SonOfLope commented on README.md
> +
Done & merci ^^

2021-05-31 14:13 UTC, cguertin14 requested changes

2021-05-31 14:13 UTC, cguertin14 commented on README.md
> +- Listening port
```suggestion
- PORT: The port on which the server will listen onto
```

2021-05-31 14:49 UTC, SonOfLope commented on README.md
> +- Listening port
Done!

2021-05-31 15:10 UTC, cguertin14 approved these changes
LGTM! 👏🏻

2021-05-31 16:03 UTC, merged