Update api/bot.go to fix invalid memory address error.
ClubCedille/mattermost2discord pull request #31
Opened 2021-06-15 02:42 UTC by SonOfLope

Jai crée une nouvelle branche car... aucune idée de comment jai crée le bordel dans l'autre PR. Sorry guys.

2021-06-15 02:44 UTC, cguertin14 requested changes
on peut rajouter des tests unitaires?

2021-06-15 03:18 UTC, cguertin14 approved these changes
lgtm 👍🏻

2021-06-15 13:05 UTC, berbiche approved these changes

2021-06-15 16:51 UTC, Vboivin approved these changes
LGTM

2021-06-15 17:29 UTC, cguertin14 requested changes

2021-06-15 17:29 UTC, cguertin14 commented on api/discord_bot_test.go
> +}
Ce test ne passe pas, il faudrait le fixer

2021-06-15 17:31 UTC, cguertin14 requested changes
le test `TestDiscordBotGetPayload` fail, donc à fix

2021-06-15 17:35 UTC, SonOfLope commented
@cguertin14  Yeah i know. J'ai un probleme lorsque je compare le expected vs actual en utilisant time.now() comme valeur de test pour timestamp. J'ai pas encore trouver de solution.

2021-06-19 22:30 UTC, berbiche commented
@SonOfLope https://github.com/jonboulle/clockwork

2021-06-25 15:12 UTC, SonOfLope reviewed
done

2021-06-25 15:14 UTC, cguertin14 approved these changes

2021-06-25 15:14 UTC, cguertin14 commented
LGTM

2021-06-25 15:16 UTC, merged